holaplex/holaplex

pages/_app.tsx, pages/storefronts.tsx
- There is a null logo url that is causing page not to render. https://aminae.holaplex.com/#/ Not sure how this happened since the fieled is required.
- Include page title for holaplex
- Adjust arweave CDN replace based on the active config
=> Fix CDN Replace, Page Title, and Arweave CDN Config Refactor

pages/index.tsx, src/modules/arweave/client.ts
Plucking by subdomain was getting storefronts who have had their subdomain changed.
Filter by pubkey which will account for any subdomain changes and give the true count of stores
=> Pull uniq by pubkey for storefronts api

package.json, pages/api/arweave/txt/[id].ts, yarn.lock
In order to use Areweave CDN on Metaplex stores the endpoint must set CORs for all sites.
The CDN has also been updated to forward the origin header from the upstream.
=> Add cors to txt endpoints

pages/nfts/new.tsx, src/modules/nfts/components/wizard/Upload.tsx, src/modules/nfts/components/wizard/Verify.tsx
If a user tries to upload a file with the same name(and file extension) as a previously uploaded file (upload meaning putting it into the browser with a file input tag, not IPFS) the system should allow it, but tack on a _1 (2,3..) at the end of the file name. The alternative being to just skip the "new" file.
Sooo: User tries to upload "image.png" two times, the system gets "image.png" and "image_1.png", and the minting process continues.
=> fix: restored image duplicate handeling

src/common/components/elements/StorePreview.tsx
Add bg for avatar the same as the card used when logo is transparent.
=> Featured Storefront Avatar Background Color

pages/nfts/new.tsx
Fixes issue #122 
Example NFT with correct metadata: https://solscan.io/token/4MHHq6NnE3gw18X9C8pCkFEyHPzg5oqo2DCDgCrZsnPL?cluster=devnet#metadata
=> Fix: Add correct collection metadata per Metaplex NFT Standard

pages/nfts/new.tsx, src/modules/nfts/components/wizard/InfoScreen.tsx, src/modules/nfts/components/wizard/Summary.tsx
Adds the ability to set both a collection name and collection family in the non-storefront minting process (from https://holaplex.com/nfts/new).
Tested with and without metadata, and with both single and multi-mints:
https://solscan.io/token/3fikcQcaDDC9zzswgxgQJSMA9P4Rqp2K8wwzHSmnFce3?cluster=devnet#metadata
https://solscan.io/token/J98UZxnvZLFQ2ijZFFEd9fPh32DK5WEvniV7wggeTyJs?cluster=devnet#metadata
https://solscan.io/token/CbTGRB1hxHCpB3pwFWkmThsFyyPZw37tFmfLZBxKkuKi?cluster=devnet#metadata
https://solscan.io/token/9cEPw4Y3ZkfSQY3hwEJEYMfBt3Y3NrWKatN6c7kBSWkF?cluster=devnet#metadata
**UI Screenshots:**
=> Add ability to set both collection name and family

pages/storefront/edit.tsx, src/common/components/elements/AppHeader.tsx, src/common/components/presentational/CommunityFundInfo.tsx, src/modules/nfts/components/wizard/RoyaltiesCreators.tsx
Initially just a small PR to change the wording of Metainfo to Store info in the Store creator, but ended up with the following
- the actual change for meta info -> store info
- added an "Edit store" link/button in the header. Tested on multiple resolutions. Approved by Damian.
- Updated the "royalties modal" to CommunityFund modal inline with Alex's changes
- updated the toast design in royalties page in bulk minting to be inline with the rest of the app
=> Metainfo ->  Store info

src/modules/nfts/components/wizard/InfoScreen.tsx
lines up with recent changes to metaplex repo (https://github.com/holaplex/metaplex/commit/39bdc1c665982b567a42ff72975bf3cf02ebd164)
- allows longer NFT titles by relying on buffer / bytelength test instead of char limit
- adds 500 char max for description
- makes titles optional
=> allow longer names & tweak form validation

.env.development, pages/index.tsx, src/modules/indexer/client.ts, src/modules/storefront/client.ts
- Switch to a string[] for managing the whitelist.
- Bundle stuff in sdk wrapper.
- Move filter logic for approved subdomains into getListings on the indexerSDK.
- Configure the default filter using env.
```
DISCOVERY_APPROVED_SUBDOMAINS_URL=https://bafkreighpjfnqufpddg4lbdzpltkvirjnhvarcl62myov5zlk5cro4656u.ipfs.dweb.link
NEXT_PUBLIC_DISCOVERY_DEFAULT_FILTER_BY=all
```
_Additional environment variables required to set approved list and default filter by_
=> Refactor Approved Subdomains

pages/_app.tsx, pages/about.tsx, pages/index.tsx, pages/storefront/edit.tsx, pages/storefront/new.tsx, src/common/components/elements/AppHeader.tsx, src/common/components/elements/SocialLinks.tsx, src/modules/ganalytics/AnalyticsProvider.tsx
- It's annoying to get to the social links in the footer because you have to get past all auctions in the infinite scroll component above.
- Remove footer
- Move social links component to About.
- Re-arranges topnav links into a more prioritized order.
- Adds compensating bottom padding in absence of the old footer
- Create a new look for the "Backed by" section or the social links (other than size / padding)
=> Rmv footer / Add social links to About / Re-arrange nav links

pages/api/sign-meta.ts, src/modules/metadata-signing.ts, tasks/consumers/sign-metadata.ts
Add retry logic to metadata signing.
This is a non-zero downtime deploy at the moment. We have to delete the old queues and configuration. Will take minting offline only for a minute.
=> add retries to metadata signing

src/common/components/elements/ActivityCard.tsx, src/common/utils/index.ts
- adding regex to remove double width parameter when image urls come from Graphql
- modified href link in activity page, which was duplicating pubkeys
activity page in profiles is generating urls duplicating the profile pubkey , resulting in 404.
=> removing double width parameter - activity page duplicating pubkey

pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, pages/profiles/[publicKey]/offers.tsx, src/common/components/elements/ProfileMenu.tsx
- updated infinite scroll to only fetch 25 more
- replaced skeleton loading with a loading spinner for fetching more
- removed loading states where they weren't supposed to be showing up (i.e when no items loaded, or no more items to fetch)
- Added sticky header for filters
=> fix: loading states for infinite scroll and reduced to 25

src/common/components/elements/NFTFile.tsx
This PR removes `aspect-square` from `NFTFile` so that media on the NFT details page will be displayed in its original aspect ratio
=> #432: display NFT in original aspect ratio

pages/alpha/index.tsx, src/common/components/feed/EmptyFeedCTA.tsx, src/common/components/feed/WhoToFollowList.tsx, src/common/components/feed/feed.utils.ts, src/graphql/feed/whoToFollow.graphql, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/layouts/FeedLayout.tsx
This PR replaces the hardcoded profiles to follow in alpha with a request to the backend.
- Changed the Who to Follow query to accept a wallet address, so it only returns the wallets that are not already followed, though I left in the "filter by unfollowed" step in components for updating top follows (`src/graphql/**`)
- Use `useWhoToFollowQuery` in alpha page (`index.tsx`, `FeedLayout.tsx`)
- Pass profiles to follow data to components that were using the hardcoded list before (`EmptyFeedCTA.tsx`, `WhoToFollowList.tsx`)
- Removed unused imports and commented code throughout.
Closes #446
=> #446: use whoToFollow query for alpha

src/graphql/discover/collections/marketcap.graphql, src/graphql/discover/collections/volume.graphql, src/graphql/fragments/CollectionPreview.graphql, src/graphql/home/home.graphql, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/views/discover/discover.hooks.ts, src/views/home/home.hooks.ts
This PR is a temporary factor to remove references to the `Nft` type returned for collection NFTs. Making this change allows us to release [this indexer PR](https://github.com/holaplex/indexer/pull/612) without breaking holaplex. I will follow up the indexer release with [this holaplex PR](https://github.com/holaplex/holaplex/pull/652/files), which will refactor to use the new `Collection` type returned by some indexer queries.
=> (indexer/#604) temporarily remove collection fragment

src/components/CollectionPreviewCard.tsx, src/views/discover/discover.hooks.ts, src/views/home/home.hooks.ts
This PR converts the lamports returned for floor price by the indexer into SOL. It also refactors the collection preview stats to account for the smaller preview cards
=> #630: fix collection stats

src/components/CardGrid.tsx, src/components/ProfilePreviewCard.tsx, src/hooks/useApolloQuery.ts, src/pages/discover/collections.tsx, src/pages/discover/profiles.tsx, src/views/discover/discover.hooks.ts
- Add preview state for profiles
- Instead of has more spinner show a row of preview cards
- Stop show the "no data" fallback text for a moment while the page is initializing
- Dismiss the has more when no more results returned from the api
=> Discover Card Grid Adjustments

src/pages/index.tsx
- For the top vol and marketcap always do the query based on the top of today and the previous day.
=> [Fix] Top Volume and Marketcap based on start of each day
