pages/index.tsx, src/modules/arweave/client.ts
Releases updates to arweave txt endpoint that adds CORs.
=> Release CORS on Arweave TXT Endpoint

src/modules/arweave/client.ts
This reverts commit c4b333ef5c9eef464cfe82059f0ed01e49096847.
=> Revert "Tweaked Arweave storefront query."

config/nginx.conf.erb
increase max file size to 100mb for big NFTS
=> set max file size to 100MB

pages/_app.tsx, pages/about.tsx, pages/index.tsx
=> Clean up Black+White Theme

pages/_app.tsx, pages/about.tsx
Attempting to resolve this infrequent layout bug on the about page.
=> About Page Layout Tweak

pages/nfts/new.tsx, src/modules/nfts/components/wizard/Verify.tsx
- Fixes bug where images wouldn't clear out of state if navigating back to the upload step
=> fix: Clear form if navigating back from verify step

pages/nfts/new.tsx, src/common/components/presentational/FeesModalContent.tsx, src/modules/nfts/components/wizard/RoyaltiesCreators.tsx, src/modules/nfts/components/wizard/Summary.tsx
Ensure Holaplex is the last creator in the creator array when uploaded to Metadata.
1 commit is a hotfix
2 commit is a refactor that removes the holaplex from the form / application state
=> Holaplex creator last

src/modules/nfts/components/wizard/MintInProgress.tsx, src/modules/nfts/components/wizard/RoyaltiesCreators.tsx, src/modules/nfts/components/wizard/Summary.tsx
Allow users to retry if IPFS upload of assets failed with notification
https://holaplex.atlassian.net/browse/HOLA-155?atlOrigin=eyJpIjoiMDZkNzE2NDVjZWJiNDNjYjgyYTk4MGQ1MzVlNTdkMDIiLCJwIjoiaiJ9
=> HOLA-155 fix: show error toast and allow retry ipfs upload

.env, .env.development, src/common/components/elements/ListingPreview.tsx
Leverage the brand new ipfs.cache.holaplex.com
=> HOLA-1 add IPFS cdn

src/modules/nfts/components/wizard/RoyaltiesCreators.tsx
users currently unable to mint
narrowed down issue to latest commit in RoyaltiesCreators.tsx
this PR will revert to the previous state until we figure out what exactly is happening
=> hot fix: revert RoyaltiesCreators.tsx

src/common/components/elements/ListingPreview.tsx, src/modules/utils/callMetaplexIndexerRPC.ts
It should not be "Ends in 0 days"
- Works on localhost and deploying to .dev at time of PR
- Moves  date parsing from native new Date(endTime) (which differs between browsers) to luxxon (library)
=> fix: countdown on safari

src/modules/utils/callMetaplexIndexerRPC.ts
- fixes countdown across safari (and hopefully mobile) browsers
- adds scam monke store to blacklist
=> Countdown fix and blacklist update

src/common/components/elements/ListingPreview.tsx
-Fixes countdowns going into negative numbers. Defaults to an empty span instead.
=> fix: no more negative countdowns

pages/index.tsx
- Set sort to the one just selected by the user not the current sort.
=> [Hotfix] Changing Disco Sorts

ant-theme.less, pages/index.tsx, src/common/components/elements/AppHeader.tsx, src/common/components/elements/Button.tsx, src/common/components/elements/FontSelect.tsx, src/common/components/elements/ListingPreview.tsx, src/common/components/elements/NFTPreviewGrid.tsx, src/common/components/elements/Price.tsx, src/common/components/elements/StorePreview.tsx, src/common/components/presentational/CommunityFundInfo.tsx, src/common/styles/globals.css, src/modules/nfts/components/wizard/InfoScreen.tsx, src/modules/nfts/components/wizard/PriceSummary.tsx, src/modules/nfts/components/wizard/RoyaltiesCreators.tsx, src/modules/nfts/components/wizard/Upload.tsx, src/modules/nfts/components/wizard/Verify.tsx, src/modules/storefront/editor.tsx
- Changes holaplex.com font to Inter (from Nunito)
- Makes black background into dark grey and white font color ever-so-slightly softer to be easier on the eyes
- Adjust font weights as needed
- Slightly increase left / right margin at small laptop / tablet break points (no changes on mobile and large screens)
- Uses SVG for sol symbol instead of a unicode character
- Sets Inter as the default font for storefronts in the store setup/edit flow
- Adds font smoothing
- various other minor adjustments
All per discussions with @bellebellesol
Resolves #151
=> Quick disco style updates

pages/index.tsx
- Add a link to home
- change span element to anchor
- add aria role button
- add smooth effect
=> add a link to home

src/common/components/elements/ActivityContent.tsx, src/types/Unpacked.ts
=> Fix: fixes fake closed items

.env
=> Release Activity Bid State Logic for Profiles

src/modules/singletons/index.ts, src/modules/solana/buildSolana.ts, tasks/consumers/sign-metadata.ts
Allow for client to pass solana endpoint.
=> respect passed signing endpoint

pages/marketplace/new.tsx, pages/storefront/edit.tsx
- Includes the storeConfig address in the json saved for the store config.
- Switch to tailwind style button.
=> Add store config address to store config json

.env, src/common/components/elements/ActivityContent.tsx, src/common/components/elements/ListingPreview.tsx, src/common/components/elements/StorePreview.tsx, src/common/utils/index.ts
=> adding support for imgopt - deprecating images.holaplex.com

pages/profiles/[wallet]/nfts.tsx
**Fix #243 Changes**
1. Search bar's search icon and placeholder text color is changed to gray-500
2. Space between display switcher and search bar (full width now) is set to 1 rem
=> fix: fixes owned nft #243 

pages/_app.tsx
(cherry picked from commit 880d8b084ee8c67c87653b1785cebcf4214abcf8)
=> Release Ukraine Charity Banner

src/common/components/elements/MoreDropdown.tsx
Small style suggestion - links to off domain sites should open in new tab.
=> Off site links open in new page

.env.development, package.json, pages/_app.tsx, pages/nfts/[address].tsx, pages/profiles/[publicKey]/nfts.tsx, src/common/components/elements/Button.tsx, src/common/components/elements/Modal.tsx, src/common/components/forms/AcceptOfferForm.tsx, src/common/components/forms/BuyForm.tsx, src/common/components/forms/CancelOfferForm.tsx, src/common/components/forms/CancelSellForm.tsx, src/common/components/forms/OfferForm.tsx, src/common/components/forms/SellForm.tsx, src/common/components/forms/UpdateOfferForm.tsx, src/common/components/forms/UpdateSellForm.tsx, src/common/context/MultiTransaction.tsx, src/graphql/activity/activityPage.graphql, src/graphql/activity/ownedNFTs.graphql, src/graphql/apollo.ts, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/modules/utils/index.ts, tailwind.config.js, yarn.lock
closes #317
closes #319 
closes #295 
closes #300 
- Migrated all actions and forms to utilize the marketplace sdk now
- Designs and integrations for buying nfts from the profile page are implemented now
- Built a WIP multi-transaction context that is being used for Update actions that require 2 transactions
=> Feat: Migrate to SDK | Buy/Sell/Update from profile | Multi-transaction Context

.env, .env.development, pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, src/common/components/elements/ProfileMenu.tsx, src/graphql/activity/createdNFTs.graphql, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts
closes #305 
- Added created tab
- Updated `Owned` to `Collected`
- Added creator query to graphql-codegen
=> Profile Created Tab

pages/nfts/[address].tsx, pages/nfts/[address]/offers/new.tsx, pages/profiles/[publicKey]/nfts.tsx
- Fixed aspect ratio on nfts
- Fixed truncated address on offers list
- Fixed routing when deep-linking as the owner and/or not connected wallet
=> Milo/fix/bug fixes-1

src/common/components/forms/AcceptOfferForm.tsx, src/common/components/forms/BuyForm.tsx, src/common/components/forms/CancelOfferForm.tsx, src/common/components/forms/CancelSellForm.tsx, src/common/components/forms/OfferForm.tsx, src/common/components/forms/SellForm.tsx, src/common/components/forms/UpdateOfferForm.tsx, src/common/components/forms/UpdateSellForm.tsx, src/common/context/MultiTransaction.tsx
=> feat: added multi-transaction context ux to marketplace actions

src/common/context/MultiTransaction.tsx
=> fix: removed error throw

pages/profiles/[publicKey]/offers.tsx
closes #299 
implements designs: https://www.figma.com/file/DC1T92jSoSIw9rvvEJytNK/Profiles?node-id=5948%3A11151
=> Add filters to offers

package.json, pages/nfts/[address].tsx, pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, pages/profiles/[publicKey]/offers.tsx, src/common/components/CurrencyHelpers.tsx, src/common/components/forms/DownloadableNFTCard.tsx, src/common/components/forms/UpdateSellForm.tsx, src/common/context/MultiTransaction.tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/nfts/shareNFT.graphql, tailwind.config.js, yarn.lock
closes #340 
- Added basic meta tags and set up serverside rendering for listing price and offers price for future proofing
=> feat: added shareable meta tags

pages/profiles/[publicKey].tsx
- Added meta tags for the profile to utilize their banner when sharing the link elsewhere
=> feat: profile social preview

package.json, pages/nfts/[address].tsx, pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, yarn.lock
- infinite scroll on collected and created
- solscan and explorer links updated to use mintAddress
closes #336 
closes #360
=> feat: infinites scroll and solscan/explorer links

pages/_app.tsx, src/common/components/elements/FollowUnfollowButton.tsx, src/common/hooks/useMakeConnection.ts
This is to improve reaction time.
=> Moved from finalized to confirmed

pages/profiles/[publicKey]/offers.tsx
should fix issue #353 not 100% sure cause I couldn't get the development environment fully set up 😅
=> Fix: Offer Tab Ordering

pages/nfts/[address].tsx, src/common/components/elements/MoreDropdown.tsx, src/common/components/icons/Explorer.tsx, src/common/components/icons/Solscan.tsx
closes #363
- Added a details view to view mint address, and other addresses
- Fixed a bug with copying a link to an NFT that led to a 404 not found
- Updated more dropdown to be a shareable dropdown with twitter intent
=> feat: mint address details and update share button

pages/nfts/[address].tsx, pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, pages/profiles/[publicKey]/offers.tsx
- added listed and unlisted filter buttons to profile nfts
- aggregates all listings not just holaplex auction house listings (this does create some odd behavior where items will show in listed filter but not be buyable *will be fixed once we have designs for aggregate*)
- fixes #362
=> feat: listed and unlisted filters

src/common/hooks/useTwitterHandle.ts
=> add support for cardinal

pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx, pages/profiles/[publicKey]/offers.tsx
- removed counts from filter buttons
=> fix: removed counts from filter buttons

pages/nfts/[address].tsx, pages/profiles/[publicKey]/nfts.tsx, src/common/components/elements/NFTImage.tsx
- added expanded nft image component
- cleaned up padding on nft cards
closes #376
=> feat: nft-expand

pages/nfts/[address].tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/marketplace/nftMarketplace.graphql
- added video and audio support for nfts on main holaplex nft details
=> feat: added video and audio support for nft details

pages/profiles/[publicKey]/offers.tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/marketplace/offersPage.graphql
=> fix: attrib bug fix

package.json, src/common/components/search/SearchBar.tsx, src/common/components/search/SearchResults.tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/search/search.graphql, yarn.lock
Consolidated the search query into a single graphql query
Added wallet search back in
=> feat: consolidated search query

pages/_document.js, pages/nfts/[address].tsx, src/common/components/elements/NFTFile.tsx, src/common/components/elements/NFTImage.tsx
On image expand the aspect ratio should be maintained
closes #450
closes #377 
- Support vr files
=> Aspect Ratio maintained on expand

src/common/components/elements/AppHeader.tsx, src/common/components/elements/DialectNotificationsButton/BellIcon.tsx, src/common/components/elements/DialectNotificationsButton/index.tsx, src/common/components/elements/MobileMenu.tsx, src/common/components/elements/ProfileImage.tsx
closes #346 
- Removed about/faq from header
- Updated bell icon to be filled
- Added shadows to profile & notifications button
- Converted styled components to html prims and tailwind classes
- Updated mobile nav
=> feat: new navbar

src/common/components/search/SearchBar.tsx
Adds
- navbar heigh pop
- opinionated refactor
Misses
- keyboard nav for search results, made ticket -> [#468](https://github.com/holaplex/holaplex/issues/452)
- global access with a ctrl/cmd + k -> #452
=> feat: update to the search html to remove navbar height change

src/modules/notary/client.ts
Came across this suggestion in #254  what do we think?
=> fix: recommended fix from a github issue

package.json, src/common/components/search/SearchBar.tsx, yarn.lock
- disabled autocomplete
- scaffolding for keybinds
- scroll bar styling
- cleanup on bar showing
=> fix: searchbar cleanup & styling

src/common/components/home/FeaturedAuctionsSection.tsx, src/common/components/home/FeaturedBuyNowListingsSection.tsx
sets the number of columns in homepage carousels based on window size, which helps avoid the issue of some cards being differently sized from others within a carousel
=> homepage v2: dynamic carousel columns

src/common/components/elements/ListingPreview.tsx, src/common/components/home/FeaturedProfilesSection.tsx
- loading image in ListingPreview
- disallow holaplex wallet in featured profiles
=> homepage v2 cleanup

src/common/components/elements/ActivityCard.tsx
=> fix: activity img aspect ratio

src/common/components/home/Footer.tsx
- Added blog and newsletter to footer
=> update: footer update

pages/profile.tsx
- added /profile page for onboarding profiles (empty cta here)
=> feat: profile landing

pages/_app.tsx, pages/alpha/index.tsx, pages/profile.tsx, src/common/components/elements/FollowModal.tsx, src/common/components/elements/FollowUnfollowButton.tsx, src/common/components/elements/FollowerCount.tsx, src/common/components/elements/ProfileContainer.tsx, src/common/components/elements/ProfileImage.tsx, src/common/components/feed/FeedCard.tsx, src/common/components/feed/WhoToFollowList.tsx, src/common/components/home/FeaturedProfilesSection.tsx, src/common/context/AnalyticsProvider.tsx, src/common/context/ConnectedWalletProfileProvider.tsx, src/common/context/MultiTransaction.tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/profile/connectionNode.graphql, src/graphql/profile/getConnectedWalletProfileData.graphql
Adds a dedicated react context/provider for data about the connected user/profile/wallet
Will hopefully reduce a lot of boilerplate code across the board like 
- useAnchorWallet
- get the connected users follower or following list
- determine if the user already follows a wallet
- +++
=> feat: POC of connected wallet profile context

src/common/components/elements/NoProfileItems.tsx
- Changed copy to better be agnostic to the user viewing it
=> copy: changed copy to be standardized and not reference "You"

src/common/components/feed/FeedCard.tsx, src/common/components/feed/feed.utils.ts
fix: agg events are only tied to the same event creator
fix: undefined address error
=> fix: agg events cleanup

src/layouts/CollectionLayout.tsx
Added link buttons to top of the collections page
=> Collection links & details

pages/collections/[collectionAddress]/nfts.tsx, pages/profiles/[publicKey]/created.tsx, pages/profiles/[publicKey]/nfts.tsx
- correctly made infinite scroll use the correct offset
=> fix: infinite scroll will no longer skip (regression was fixed in past)

pages/nfts/[address].tsx, src/components/AcceptOfferForm.tsx, src/components/CancelOfferForm.tsx, src/components/CancelSellForm.tsx, src/components/CurrencyHelpers.tsx, src/components/OfferForm.tsx, src/components/UpdateOfferForm.tsx, src/lib/utils/index.ts, src/modules/crossmint/index.ts, src/modules/sol/sol.ts, src/views/_global/MultiTransaction.tsx
- Only show listings for the current owner
- Deposit and withdraw funds for listing and offer
- Use async for multi-transaction sender callbacks
=> Add escrow deposit and withdraw to offer and listing instructions

src/components/AcceptOfferForm.tsx, src/components/AppHeader.tsx, src/views/_global/SearchBar.tsx
The mobile nav was rendering on the page in the top right while the js for the app was being loaded in.
- Move away from styled components for the mobile nav
- Don't have a separate nav menu that needs to render for mobile
=> Refactor Mobile Nav Structure

pages/nfts/[address].tsx, src/views/collections/CollectionLayout.tsx, src/views/profiles/ProfileLayout.tsx
=> Fix Og tags to show image on twitter share

src/views/alpha/WhoToFollowList.tsx
BuyForm will operate unexpectedly when in a ReactPortal this fix should make the form state and operations consistent
=> Hot-Fix: Buy Form

src/components/NFTFile.tsx
video files now properly use the correct file
=> bug-fix: properly handle video files

src/components/BuyForm.tsx
- For buy action add deposit and offer instruction before buy
=> Fix Buy NFT

src/views/home/FeaturedMarketplacesSection.tsx, src/views/home/home.hooks.ts
=> Fixes for Featured Marketplace

src/pages/profiles/[publicKey]/collections.tsx
This was a regression that probably occured from older cold getting merged into this page
=> fix: fixed unique helper to fix duplicate collections

package.json, src/pages/_app.tsx, yarn.lock
New version of `@solana/wallet-adapter-wallets` has added support for Backpack (yet to be released).
=> Update @solana/wallet-adapter-wallets & add backpack support

src/components/CollectionPreviewCard.tsx
=> New Collection Card Design

src/components/AppHeader.tsx, src/components/CardGrid.tsx, src/components/DropdownMenu.tsx
- Add hover state to discover dropdown links
- Adjust z-index so searchbar for discover pages doesn't cover discover dropdown menu
https://github.com/holaplex/holaplex/pull/659
=> Discovery Dropdown Fixups

src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/marketplace/subdomainCheck.graphql, src/modules/auction-house/CreateAuctionHouse.ts, src/pages/marketplace/new.tsx
- Fund treasury account and fee account for SOL based auction houses to be rent exempt to ensure no "account under rent-exempt errors"
- Validate subdomain based on other marketplaces and not subdomains
- Switch to getLatestBlockHash for setting recentBlockHash on the transaction
=> Create Marketplace issue

package.json, src/pages/_app.tsx
=> add brave wallet adapter

src/components/CurrencyHelpers.tsx, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/graphql/search/search.graphql, src/views/_global/SearchBar.tsx, src/views/_global/SearchItems.tsx, src/views/_global/SearchResults.tsx
Made collection search a bit more useful by utilizing the discover top volume search to surface the most relevant collections
=> Search improvements

src/components/ActivityCard.tsx, src/components/DownloadableNFTCard.tsx, src/components/OfferForm.tsx, src/components/UpdateSellForm.tsx, src/pages/profiles/[publicKey]/activity.tsx, src/pages/profiles/[publicKey]/nfts.tsx, src/views/_global/AnalyticsProvider.tsx, src/views/_global/SearchResults.tsx, src/views/alpha/FeedCard.tsx, src/views/alpha/activity.interfaces.tsx
For those of us that like to copy addresses from the URL this should make the few times you copy and paste and address and get a different token address in solscan/explorer less frequent and should overall be an improvement for the lay persons
=> improvement: utilize mintAddress whenever possible

src/components/CookieSettings.tsx, src/graphql/fragments/FollowEventPreview.graphql, src/graphql/fragments/ListingEventPreview.graphql, src/graphql/fragments/MintEventPreview.graphql, src/graphql/fragments/OfferEventPreview.graphql, src/graphql/fragments/PurchaseEventPreview.graphql, src/graphql/indexerTypes.ssr.ts, src/graphql/indexerTypes.ts, src/pages/profiles/[publicKey]/collections.tsx, src/views/alpha/MyActivityList.tsx
- Select address from wallet object
=> Fix Wallet Queries
